services:
  primary-pg13:
    build:
      context: ..
      dockerfile: integration/primary.Dockerfile
      args:
        PG_VERSION: "13"
    container_name: replicon-primary-pg13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
      REPLICATION_PASSWORD: postgres
      REPLICATION_SLOT: replicon_demo_slot
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "55442:5432"
    volumes:
      - primary-data-pg13:/var/lib/postgresql/data
      - ./postgresql.primary.conf:/etc/postgresql/postgresql.conf:ro
      - ./pg_hba.primary.conf:/etc/postgresql/pg_hba.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf", "-c", "password_encryption=scram-sha-256"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  standby-pg13:
    image: postgres:13
    container_name: replicon-standby-pg13
    environment:
      PGDATA: /var/lib/postgresql/data
      PRIMARY_HOST: primary-pg13
      PRIMARY_PORT: "5432"
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: postgres
      REPLICATION_SLOT: replicon_demo_slot
      APPLICATION_NAME: orders-prod-standby
    depends_on:
      primary-pg13:
        condition: service_healthy
    ports:
      - "55443:5432"
    volumes:
      - standby-data-pg13:/var/lib/postgresql/data
      - ./standby-entrypoint.sh:/usr/local/bin/standby-entrypoint.sh:ro
    entrypoint: ["sh", "/usr/local/bin/standby-entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  primary-data-pg13:
  standby-data-pg13:
